name: Build Ungoogled Chromium DMG (Apple Silicon)

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main

jobs:
  check-and-build:
    runs-on: macos-14  # Uses macOS 14 runner with Apple Silicon support
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Checkout Ungoogled Chromium
      uses: actions/checkout@v4
      with:
        repository: ungoogled-software/ungoogled-chromium
        path: ungoogled-chromium
        
    - name: Install system dependencies
      run: |
        echo "Installing build dependencies..."
        brew install jq ninja cmake pkg-config
        brew list jq ninja cmake pkg-config
        
    - name: Check for new version
      id: version_check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        chmod +x .github/scripts/version_check.sh
        # Force build if triggered manually
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          ./.github/scripts/version_check.sh true "$GITHUB_TOKEN"
        else
          ./.github/scripts/version_check.sh false "$GITHUB_TOKEN"
        fi
        
    - name: Setup Python
      if: steps.version_check.outputs.new_version == 'true'
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Verify Python Setup
      if: steps.version_check.outputs.new_version == 'true'
      run: |
        python3 --version
        pip3 --version
        
    - name: Setup depot_tools
      if: steps.version_check.outputs.new_version == 'true'
      run: |
        echo "Setting up depot_tools..."
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH
        
    - name: Verify build tools
      if: steps.version_check.outputs.new_version == 'true'
      run: |
        echo "Verifying build tools..."
        export PATH="$GITHUB_WORKSPACE/depot_tools:$PATH"
        which ninja
        which gn || echo "gn not found"
        which autoninja || echo "autoninja not found"
        which gclient || echo "gclient not found"
        
    - name: Fetch Chromium source
      if: steps.version_check.outputs.new_version == 'true'
      run: |
        echo "Fetching Chromium source version ${{ steps.version_check.outputs.version }}..."
        export PATH="$GITHUB_WORKSPACE/depot_tools:$PATH"
        fetch --nohooks chromium
        cd src
        git checkout ${{ steps.version_check.outputs.version }}
        gclient sync -D --force --reset
        
    - name: Apply Ungoogled Chromium patches
      if: steps.version_check.outputs.new_version == 'true'
      run: |
        echo "Applying Ungoogled Chromium patches..."
        cp -r ungoogled-chromium/* src/
        cd src
        python3 utils/apply_patches.py
        
    - name: Build Chromium
      if: steps.version_check.outputs.new_version == 'true'
      run: |
        echo "Building Chromium for Apple Silicon..."
        export PATH="$GITHUB_WORKSPACE/depot_tools:$PATH"
        cd src
        gn gen out/Default --args='target_cpu="arm64" is_debug=false enable_nacl=false use_system_xcode=true'
        autoninja -C out/Default chrome
        
    - name: Create DMG
      if: steps.version_check.outputs.new_version == 'true'
      run: |
        echo "Creating DMG package..."
        cd src
        chrome/installer/mac/pkg-dmg \
          --source out/Default/Chromium.app \
          --target "ungoogled-chromium-${{ steps.version_check.outputs.version }}-arm64.dmg" \
          --volname "Ungoogled Chromium" \
          --symlink /Applications
          
    - name: Create Release
      if: steps.version_check.outputs.new_version == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version_check.outputs.version }}
        name: "Ungoogled Chromium ${{ steps.version_check.outputs.version }} (Apple Silicon)"
        files: src/ungoogled-chromium-${{ steps.version_check.outputs.version }}-arm64.dmg
        generate_release_notes: true
        body: |
          Ungoogled Chromium ${{ steps.version_check.outputs.version }} built for Apple Silicon (arm64)
          
          This is an automated build of Ungoogled Chromium for Apple Silicon Macs.
          - Built from: ungoogled-software/ungoogled-chromium@${{ steps.version_check.outputs.version }}
          - Architecture: arm64 (Apple Silicon)
          - Built on: macOS 14 runner
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 